### ISSUE TITLE
Add new .lang files

### ISSUE THREAD

**Issue by osiewicz** [osiewicz/Statula#7]
Open up .en-gb,lang and do it on the fly. Ideally your translation should be reviewed by someone else.

**Comment by tunnelsnake** [comment]
I can do spanish!

**Comment by tunnelsnake** [comment]
#10

**Comment by rogersec** [comment]
I'll try to add portuguese.

**Comment by rafaelkalan** [comment]
Pt-Br Done #11

**Comment by Leoche** [comment]
French translations done :) #15

**Comment by Tocive** [comment]
Created a PR for a Dutch translation

**Comment by osiewicz** [comment]
Closing for now. See: https://osiewicz.github.io/2018/10/15/Language-barriers.html
